apps/productos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'producto'

urlpatterns = [
    path('', login_required(views.ProductoListView.as_view()), name='index'),
    path('detalle-producto/<int:pk>/', login_required(views.ProductoDetailView.as_view()), name='detalle_producto'),
    path('crear-producto/', views.ProductoCreateView.as_view(), name='crear_producto'),
    path('actualizar-producto/<int:pk>/', views.ProductoUpdateView.as_view(), name='actualizar_producto'),
    path('eliminar-producto/<int:pk>/', views.ProductoDeleteView.as_view(), name='eliminar_producto')
]

tienda_mascotas/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.productos.urls', namespace='producto')),
    path('accounts/', include('apps.users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

apps/productos/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone

# Create your models here.

class Marca(models.Model):
    nombre_marca = models.CharField('Marca', max_length=200, null=False, blank=False)
    
    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'
        
    def __str__(self):
        return self.nombre_marca
    
class Categoria(models.Model):
    categoria_producto = models.CharField('Categoría', max_length=100, null=False, blank=False)
    
    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'
        
    def __str__(self):
        return self.categoria_producto
    
class Producto(models.Model):
    nombre_producto = models.CharField('Nombre del Producto', unique=True, max_length=200, null=False, blank=False)
    imagen_producto = models.ImageField('Imagen del producto', upload_to='productos/', null=False, blank=False)
    stock = models.IntegerField('Cantidad', default=0)
    precio = models.FloatField('Precio', default=00.0)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha_vencimiento = models.DateTimeField('Fecha de vencimiento', null=False, blank=False)
    fecha_creacion = models.DateTimeField('Fecha de creación', auto_now_add=True)
    public = models.BooleanField('Público', default=True)
    
    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        
    @admin.display(
        boolean=True,
        description='Expiración del producto:'
    )
    
    def producto_expirado(self):
        producto_expirado = self.fecha_vencimiento < timezone.now()
        if (producto_expirado and self.public) or self.stock == 0:
            self.public = False
            self.save()
        elif not producto_expirado and not self.public and self.stock > 0:
            self.public = True
            self.save()
        return producto_expirado
    
    def __str__(self):
        return self.nombre_producto
        

apps/productos/forms.py
from datetime import timedelta

from django import forms
from django.utils import timezone, dateformat

from .models import Producto

formatted_date = dateformat.format(timezone.now(), 'Y-m-d H:i')

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        inputClass = 'mb-2 bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500'
        fields = ['nombre_producto', 'imagen_producto', 'stock', 'precio', 'marca', 'categoria', 'fecha_vencimiento']
        labels = {
            'nombre_producto': 'Nombre del producto',
            'imagen_producto': 'Imagen del producto',
            'stock': 'Cantidad disponible',
            'marca': 'Marca',
            'categoria': 'Categoría',
            'fecha_vencimiento': 'Fecha de vencimiento'
        }
        
        widgets = {
            'nombre_producto': forms.TextInput(
                attrs= {
                    'class': inputClass,
                    'placeholder': 'Nombre del producto'
                }
            ),
            'stock': forms.NumberInput(
                attrs={
                    'class': inputClass 
                }
            ),
            'precio': forms.NumberInput(
                attrs={
                    'class': inputClass 
                }
            ),
            'marca': forms.Select(
                attrs={
                    'class': inputClass 
                }
            ),
            'categoria': forms.Select(
                attrs={
                        'class': inputClass 
                    }
            ),
            'fecha_vencimiento': forms.DateTimeInput(
                format = '%Y-%m-%d %H:%M',
                attrs = {
                    #'type': 'date',
                    'class': inputClass,
                    'value': formatted_date,
                }
            )
        }
        
        def clean_stock(self):
            stock = self.cleaned_data.get('stock')
            if stock < 1 or stock > 100:
                raise forms.ValidationError('Ingrese un número entre 0 y 100', code='invalid')
            return stock
        
        def clean_price(self):
            precio = self.cleaned_data.get('precio')
            if precio < 1:
                raise forms.ValidationError('El precio debe ser mayor a 0', code='invalid')
            return precio
        
        def clean_fecha_vencimiento(self):
            fecha_vencimiento = self.cleaned_data['fecha_vencimiento']
            if fecha_vencimiento < (timezone.now() + timedelta(10)):
                self.add_error('fecha_vencimiento', 'La fecha de vencimiento debe ser a partir de 10 días desde hoy')
            return fecha_vencimiento

apps/productos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    View,
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from .models import Categoria, Producto
from .forms import ProductoForm
#from apps.sale.forms import AddCarForm

# Create your views here.

def home(request):
    productos = Producto.objects.all()
    return render(request, 'list.html', {'productos': productos})

class ProductoView(View):
    def get(self, request, *args, **kwargs):
        productos = Producto.objects.all()
        categorias = Categoria.objects.all()
        
        return render(request, "list.html", {'productos':productos, 'categorias': categorias})
    
    def post(self, request, *args, **kwargs):
        print("Dentro del método post()")
        return self.get(request)
    
class ProductoTemplateView(TemplateView, ProductoView):
    template_name = 'base.html'
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)
    
class ProductoListView(ListView):
    template_name = 'productos/producto_list.html'
    context_object_name = 'productos'
    paginate_by = 4
    def get_queryset(self):
        productos = Producto.objects.filter(
            public=True,
            stock__gt = 0
        ).order_by('-precio')
        
        return productos
    
class ProductoDetailView(DetailView):
    model = Producto
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #context['form'] = AddCarForm
        return context

class ProductoCreateView(LoginRequiredMixin, CreateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('producto:index')
    
class ProductoUpdateView(LoginRequiredMixin, UpdateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('producto:index')
    
class ProductoDeleteView(LoginRequiredMixin, DeleteView): 
    model = Producto
    success_url = reverse_lazy('producto:index')
    def post(self, pk):
        producto = self.model.objects.get(id=pk)
        producto.public = False
        producto.save()
        return redirect(self.success_url)

templates/productos/producto_confirmar_eliminar.html
{% extends 'base.html' %}

{% block title %}
Eliminar producto
{% endblock title %}


{% block content %}
    <form method="POST">
        <h2>¿Está seguro que desea eliminar el producto {{ object.nombre_producto }}?</h2>
         {% csrf_token %}
        <button class="btn danger" type="submit">Eliminar</button>
    </form>
    <br>
    <a href="{% url 'producto:index' %}">Cancelar</a>
{% endblock %}

templates/productos/producto_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="text-center mt-8 mb-6">
    <p class="text-center"><strong class="text-xl">Detalle del producto</strong></p>
</div>
<div class="flex justify-center">
    <div class="flex flex-row mb-8 bg-white shadow-md rounded px-8 py-8">
        <img src="{{ producto.imagen_producto.url }}">
        <div>
            <strong class="color-blue">Nombre del producto: </strong>
            <p>{{object.nombre_producto}}</p>
            <strong>Cantidad disponible: </strong>
            <p>{{object.stock}}</p>
            <strong>Precio: </strong>
            <p>{{object.precio}}</p>
            <strong>Marca: </strong>
            <p>{{object.marca}}</p>
            <strong>Categoría: </strong>
            <p>{{object.categoria}}</p>
            <strong>Fecha de vencimiento: </strong>
            <p>{{object.fecha_vencimiento}}</p>
            <br>
            <form action="#{% comment %} {% url 'sale:add_car' %} {% endcomment %}" method="post">
                <input type="hidden" name="id_product" value="{{ object.id }}">
                {{form.as_p}}
                {% csrf_token %}
                <div>
                    <a href="{% url 'producto:index' %}" type="button" class="bg-red-400 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Cancelar</a>
                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                        Agregar al carrito</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
    

templates/productos/producto_form.html
{% extends 'base.html' %}

{% block title %}Agregar producto{% endblock title %}

{% block content %}
<div class="flex justify-center">
    <form action="" method="POST" enctype="multipart/form-data" class="mt-8 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="text-center mb-4">
            <p class="text-center"><strong class="text-xl">Agregar producto</strong></p>
        </div>
        {{ form.as_p }}
        {% csrf_token %}
        <div class="flex justify-between px-10">
            <a class="bg-red-400 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" href="{% url 'producto:index' %}" type="button">Cancelar</a>
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">Aceptar</button>
        </div>
    </form>
</div>
{% endblock content %}

templates/productos/producto_list.html
{% extends 'base.html' %}

{% block title %}
PataPet
{% endblock title %}

{% block categorias %}
<div @click.away="open = false" class="relative" x-data="{ open: false }">
    <button @click="open = !open" class="flex flex-row items-center w-full text-left rounded-lg focus:outline-none text-gray-800 hover:text-black">
        <span>Categorías</span>
        <svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
    <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48">
    {% for categoria in categorias %}      
        <div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">
            <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" 
                href="#">Link #1 {{ categoria }}</a>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock categorias %}

{% block content %}
<div class="flex justify-center grid gap-6 lg:grid-cols-4 grid-cols-2 mx-8 my-8 pt-2">
    {% for producto in productos %}      
        <div class="mx-8 bg-white rounded-2xl shadow-xl md:px-8 md:py-12 px-4 py-4 lg:px-8 align-center">
                <img class="object-center h-40" src="{{ producto.imagen_producto.url }}"><br>
            <div class="">
                <h2 class="text-center">
                    <a class="decoration-sky-500/30 hover:text-blue-700" href="{% url 'producto:detalle_producto' producto.id %}"><strong>{{ producto.nombre_producto }}</strong></a>
                </h2><br>
                <p>Cantidad: {{ producto.stock }}</p>
                <p>Precio: {{ producto.precio }} Bs.</p>
                <p>Marca: {{ producto.marca }}</p>
                <p>Categoría: {{ producto.categoria }}</p>
                <br><hr>
                <div class="flex justify-between">
                    <a class="hover:underline" href="{% url 'producto:actualizar_producto' producto.id %}">Editar</a>
                    <a class="hover:underline" href="{% url 'producto:eliminar_producto' producto.id %}"><p>Eliminar</p></a>
                </div>
            </div>
        </div>
    {% empty %}
        <p class="description">No hay productos registrados</p>
    {% endfor %}
</div>

{% include 'paginacion.html' with page_obj=page_obj %}

<br>
{% comment %} <a href="{% url 'sale:sale_product' %}#">See products to send</a> {% endcomment %}
{% endblock content %}